// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/services/seminar (interfaces: OwnerRepoAdapter)
//
// Generated by this command:
//
//	mockgen -destination=../../test/services/seminar_mock/adapter_mock.go -package=seminar_mock . OwnerRepoAdapter
//

// Package seminar_mock is a generated GoMock package.
package seminar_mock

import (
	context "context"
	reflect "reflect"

	image "github.com/mikhail5545/product-service-go/internal/models/image"
	image_owner "github.com/mikhail5545/product-service-go/internal/types/image_owner"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOwnerRepoAdapter is a mock of OwnerRepoAdapter interface.
type MockOwnerRepoAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockOwnerRepoAdapterMockRecorder
	isgomock struct{}
}

// MockOwnerRepoAdapterMockRecorder is the mock recorder for MockOwnerRepoAdapter.
type MockOwnerRepoAdapterMockRecorder struct {
	mock *MockOwnerRepoAdapter
}

// NewMockOwnerRepoAdapter creates a new mock instance.
func NewMockOwnerRepoAdapter(ctrl *gomock.Controller) *MockOwnerRepoAdapter {
	mock := &MockOwnerRepoAdapter{ctrl: ctrl}
	mock.recorder = &MockOwnerRepoAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnerRepoAdapter) EXPECT() *MockOwnerRepoAdapterMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockOwnerRepoAdapter) AddImage(ctx context.Context, owner image_owner.Owner, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", ctx, owner, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImage indicates an expected call of AddImage.
func (mr *MockOwnerRepoAdapterMockRecorder) AddImage(ctx, owner, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).AddImage), ctx, owner, arg2)
}

// AddImageBatch mocks base method.
func (m *MockOwnerRepoAdapter) AddImageBatch(ctx context.Context, owners []image_owner.Owner, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImageBatch", ctx, owners, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImageBatch indicates an expected call of AddImageBatch.
func (mr *MockOwnerRepoAdapterMockRecorder) AddImageBatch(ctx, owners, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImageBatch", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).AddImageBatch), ctx, owners, arg2)
}

// BatchUpdate mocks base method.
func (m *MockOwnerRepoAdapter) BatchUpdate(ctx context.Context, owners []image_owner.Owner, opt uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, owners, opt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockOwnerRepoAdapterMockRecorder) BatchUpdate(ctx, owners, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).BatchUpdate), ctx, owners, opt)
}

// DB mocks base method.
func (m *MockOwnerRepoAdapter) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockOwnerRepoAdapterMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).DB))
}

// DecrementImageCount mocks base method.
func (m *MockOwnerRepoAdapter) DecrementImageCount(ctx context.Context, ownerIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementImageCount", ctx, ownerIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementImageCount indicates an expected call of DecrementImageCount.
func (mr *MockOwnerRepoAdapterMockRecorder) DecrementImageCount(ctx, ownerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementImageCount", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).DecrementImageCount), ctx, ownerIDs)
}

// DeleteImage mocks base method.
func (m *MockOwnerRepoAdapter) DeleteImage(ctx context.Context, owner image_owner.Owner, mediaSvcID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, owner, mediaSvcID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockOwnerRepoAdapterMockRecorder) DeleteImage(ctx, owner, mediaSvcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).DeleteImage), ctx, owner, mediaSvcID)
}

// FindOwnerIDsByImageID mocks base method.
func (m *MockOwnerRepoAdapter) FindOwnerIDsByImageID(ctx context.Context, mediaSvcID string, ownerIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOwnerIDsByImageID", ctx, mediaSvcID, ownerIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOwnerIDsByImageID indicates an expected call of FindOwnerIDsByImageID.
func (mr *MockOwnerRepoAdapterMockRecorder) FindOwnerIDsByImageID(ctx, mediaSvcID, ownerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOwnerIDsByImageID", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).FindOwnerIDsByImageID), ctx, mediaSvcID, ownerIDs)
}

// GetWithUnpublished mocks base method.
func (m *MockOwnerRepoAdapter) GetWithUnpublished(ctx context.Context, id string) (image_owner.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(image_owner.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockOwnerRepoAdapterMockRecorder) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).GetWithUnpublished), ctx, id)
}

// ListWithUnpublishedByIDs mocks base method.
func (m *MockOwnerRepoAdapter) ListWithUnpublishedByIDs(ctx context.Context, ids ...string) ([]image_owner.Owner, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListWithUnpublishedByIDs", varargs...)
	ret0, _ := ret[0].([]image_owner.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithUnpublishedByIDs indicates an expected call of ListWithUnpublishedByIDs.
func (mr *MockOwnerRepoAdapterMockRecorder) ListWithUnpublishedByIDs(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithUnpublishedByIDs", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).ListWithUnpublishedByIDs), varargs...)
}

// WithTx mocks base method.
func (m *MockOwnerRepoAdapter) WithTx(tx *gorm.DB) image_owner.OwnerRepo[image_owner.Owner] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(image_owner.OwnerRepo[image_owner.Owner])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockOwnerRepoAdapterMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockOwnerRepoAdapter)(nil).WithTx), tx)
}
