// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/database/training_session (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../test/database/training_session_mock/repo_mock.go -package=training_session_mock github.com/mikhail5545/product-service-go/internal/database/training_session Repository
//

// Package training_session_mock is a generated GoMock package.
package training_session_mock

import (
	context "context"
	reflect "reflect"

	trainingsession "github.com/mikhail5545/product-service-go/internal/database/training_session"
	trainingsession0 "github.com/mikhail5545/product-service-go/internal/models/training_session"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx)
}

// CountDeleted mocks base method.
func (m *MockRepository) CountDeleted(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDeleted", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDeleted indicates an expected call of CountDeleted.
func (mr *MockRepositoryMockRecorder) CountDeleted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDeleted", reflect.TypeOf((*MockRepository)(nil).CountDeleted), ctx)
}

// CountUnpublished mocks base method.
func (m *MockRepository) CountUnpublished(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnpublished", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnpublished indicates an expected call of CountUnpublished.
func (mr *MockRepositoryMockRecorder) CountUnpublished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnpublished", reflect.TypeOf((*MockRepository)(nil).CountUnpublished), ctx)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, ts *trainingsession0.TrainingSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, ts)
}

// DB mocks base method.
func (m *MockRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockRepository)(nil).DB))
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// DeletePermanent mocks base method.
func (m *MockRepository) DeletePermanent(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanent", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermanent indicates an expected call of DeletePermanent.
func (mr *MockRepositoryMockRecorder) DeletePermanent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanent", reflect.TypeOf((*MockRepository)(nil).DeletePermanent), ctx, id)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id string) (*trainingsession0.TrainingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*trainingsession0.TrainingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// GetWithDeleted mocks base method.
func (m *MockRepository) GetWithDeleted(ctx context.Context, id string) (*trainingsession0.TrainingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeleted", ctx, id)
	ret0, _ := ret[0].(*trainingsession0.TrainingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeleted indicates an expected call of GetWithDeleted.
func (mr *MockRepositoryMockRecorder) GetWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeleted", reflect.TypeOf((*MockRepository)(nil).GetWithDeleted), ctx, id)
}

// GetWithUnpublished mocks base method.
func (m *MockRepository) GetWithUnpublished(ctx context.Context, id string) (*trainingsession0.TrainingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(*trainingsession0.TrainingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockRepositoryMockRecorder) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockRepository)(nil).GetWithUnpublished), ctx, id)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, limit, offset int) ([]trainingsession0.TrainingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]trainingsession0.TrainingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, limit, offset)
}

// ListDeleted mocks base method.
func (m *MockRepository) ListDeleted(ctx context.Context, limit, offset int) ([]trainingsession0.TrainingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeleted", ctx, limit, offset)
	ret0, _ := ret[0].([]trainingsession0.TrainingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeleted indicates an expected call of ListDeleted.
func (mr *MockRepositoryMockRecorder) ListDeleted(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeleted", reflect.TypeOf((*MockRepository)(nil).ListDeleted), ctx, limit, offset)
}

// ListUnpublished mocks base method.
func (m *MockRepository) ListUnpublished(ctx context.Context, limit, offset int) ([]trainingsession0.TrainingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, limit, offset)
	ret0, _ := ret[0].([]trainingsession0.TrainingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockRepositoryMockRecorder) ListUnpublished(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockRepository)(nil).ListUnpublished), ctx, limit, offset)
}

// Restore mocks base method.
func (m *MockRepository) Restore(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRepository)(nil).Restore), ctx, id)
}

// Select mocks base method.
func (m *MockRepository) Select(ctx context.Context, id string, fields ...string) (*trainingsession0.TrainingSession, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Select", varargs...)
	ret0, _ := ret[0].(*trainingsession0.TrainingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepositoryMockRecorder) Select(ctx, id any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepository)(nil).Select), varargs...)
}

// SetInStock mocks base method.
func (m *MockRepository) SetInStock(ctx context.Context, id string, inStock bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInStock", ctx, id, inStock)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInStock indicates an expected call of SetInStock.
func (mr *MockRepositoryMockRecorder) SetInStock(ctx, id, inStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInStock", reflect.TypeOf((*MockRepository)(nil).SetInStock), ctx, id, inStock)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, ts *trainingsession0.TrainingSession, updates any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ts, updates)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, ts, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, ts, updates)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *gorm.DB) trainingsession.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(trainingsession.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
