// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/types/video_owner (interfaces: OwnerRepo)
//
// Generated by this command:
//
//	mockgen -destination=../../test/types/video_owner_mock/repo_mock.go -package=video_owner_mock . OwnerRepo
//

// Package video_owner_mock is a generated GoMock package.
package video_owner_mock

import (
	context "context"
	reflect "reflect"

	video_owner "github.com/mikhail5545/product-service-go/internal/types/video_owner"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOwnerRepo is a mock of OwnerRepo interface.
type MockOwnerRepo[T video_owner.Owner] struct {
	ctrl     *gomock.Controller
	recorder *MockOwnerRepoMockRecorder[T]
	isgomock struct{}
}

// MockOwnerRepoMockRecorder is the mock recorder for MockOwnerRepo.
type MockOwnerRepoMockRecorder[T video_owner.Owner] struct {
	mock *MockOwnerRepo[T]
}

// NewMockOwnerRepo creates a new mock instance.
func NewMockOwnerRepo[T video_owner.Owner](ctrl *gomock.Controller) *MockOwnerRepo[T] {
	mock := &MockOwnerRepo[T]{ctrl: ctrl}
	mock.recorder = &MockOwnerRepoMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnerRepo[T]) EXPECT() *MockOwnerRepoMockRecorder[T] {
	return m.recorder
}

// DB mocks base method.
func (m *MockOwnerRepo[T]) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockOwnerRepoMockRecorder[T]) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockOwnerRepo[T])(nil).DB))
}

// GetWithUnpublished mocks base method.
func (m *MockOwnerRepo[T]) GetWithUnpublished(ctx context.Context, id string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockOwnerRepoMockRecorder[T]) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockOwnerRepo[T])(nil).GetWithUnpublished), ctx, id)
}

// UpdateVideoID mocks base method.
func (m *MockOwnerRepo[T]) UpdateVideoID(ctx context.Context, ownerID string, videoID *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoID", ctx, ownerID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoID indicates an expected call of UpdateVideoID.
func (mr *MockOwnerRepoMockRecorder[T]) UpdateVideoID(ctx, ownerID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoID", reflect.TypeOf((*MockOwnerRepo[T])(nil).UpdateVideoID), ctx, ownerID, videoID)
}

// WithTx mocks base method.
func (m *MockOwnerRepo[T]) WithTx(tx *gorm.DB) video_owner.OwnerRepo[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(video_owner.OwnerRepo[T])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockOwnerRepoMockRecorder[T]) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockOwnerRepo[T])(nil).WithTx), tx)
}
