// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/services/course (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../test/services/course_mock/service_mock.go -package=course_mock . Service
//

// Package course_mock is a generated GoMock package.
package course_mock

import (
	context "context"
	reflect "reflect"

	course "github.com/mikhail5545/product-service-go/internal/models/course"
	image "github.com/mikhail5545/product-service-go/internal/models/image"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockService) AddImage(ctx context.Context, req *image.AddRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImage indicates an expected call of AddImage.
func (mr *MockServiceMockRecorder) AddImage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockService)(nil).AddImage), ctx, req)
}

// AddImageBatch mocks base method.
func (m *MockService) AddImageBatch(ctx context.Context, req *image.AddBatchRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImageBatch", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddImageBatch indicates an expected call of AddImageBatch.
func (mr *MockServiceMockRecorder) AddImageBatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImageBatch", reflect.TypeOf((*MockService)(nil).AddImageBatch), ctx, req)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req *course.CreateRequest) (*course.CreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*course.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// DeleteImage mocks base method.
func (m *MockService) DeleteImage(ctx context.Context, req *image.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockServiceMockRecorder) DeleteImage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockService)(nil).DeleteImage), ctx, req)
}

// DeleteImageBatch mocks base method.
func (m *MockService) DeleteImageBatch(ctx context.Context, req *image.DeleteBatchRequst) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImageBatch", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteImageBatch indicates an expected call of DeleteImageBatch.
func (mr *MockServiceMockRecorder) DeleteImageBatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImageBatch", reflect.TypeOf((*MockService)(nil).DeleteImageBatch), ctx, req)
}

// DeletePermanent mocks base method.
func (m *MockService) DeletePermanent(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermanent indicates an expected call of DeletePermanent.
func (mr *MockServiceMockRecorder) DeletePermanent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanent", reflect.TypeOf((*MockService)(nil).DeletePermanent), ctx, id)
}

// Get mocks base method.
func (m *MockService) Get(ctx context.Context, id string) (*course.CourseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*course.CourseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService)(nil).Get), ctx, id)
}

// GetReduced mocks base method.
func (m *MockService) GetReduced(ctx context.Context, id string) (*course.CourseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReduced", ctx, id)
	ret0, _ := ret[0].(*course.CourseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReduced indicates an expected call of GetReduced.
func (mr *MockServiceMockRecorder) GetReduced(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReduced", reflect.TypeOf((*MockService)(nil).GetReduced), ctx, id)
}

// GetReducedWithDeleted mocks base method.
func (m *MockService) GetReducedWithDeleted(ctx context.Context, id string) (*course.CourseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReducedWithDeleted", ctx, id)
	ret0, _ := ret[0].(*course.CourseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReducedWithDeleted indicates an expected call of GetReducedWithDeleted.
func (mr *MockServiceMockRecorder) GetReducedWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReducedWithDeleted", reflect.TypeOf((*MockService)(nil).GetReducedWithDeleted), ctx, id)
}

// GetWithDeleted mocks base method.
func (m *MockService) GetWithDeleted(ctx context.Context, id string) (*course.CourseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeleted", ctx, id)
	ret0, _ := ret[0].(*course.CourseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeleted indicates an expected call of GetWithDeleted.
func (mr *MockServiceMockRecorder) GetWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeleted", reflect.TypeOf((*MockService)(nil).GetWithDeleted), ctx, id)
}

// GetWithUnpublished mocks base method.
func (m *MockService) GetWithUnpublished(ctx context.Context, id string) (*course.CourseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(*course.CourseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockServiceMockRecorder) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockService)(nil).GetWithUnpublished), ctx, id)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, limit, offset int) ([]course.CourseDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]course.CourseDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, limit, offset)
}

// ListDeleted mocks base method.
func (m *MockService) ListDeleted(ctx context.Context, limit, offset int) ([]course.CourseDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeleted", ctx, limit, offset)
	ret0, _ := ret[0].([]course.CourseDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDeleted indicates an expected call of ListDeleted.
func (mr *MockServiceMockRecorder) ListDeleted(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeleted", reflect.TypeOf((*MockService)(nil).ListDeleted), ctx, limit, offset)
}

// ListUnpublished mocks base method.
func (m *MockService) ListUnpublished(ctx context.Context, limit, offset int) ([]course.CourseDetails, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, limit, offset)
	ret0, _ := ret[0].([]course.CourseDetails)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockServiceMockRecorder) ListUnpublished(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockService)(nil).ListUnpublished), ctx, limit, offset)
}

// Publish mocks base method.
func (m *MockService) Publish(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockServiceMockRecorder) Publish(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockService)(nil).Publish), ctx, id)
}

// Restore mocks base method.
func (m *MockService) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockServiceMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockService)(nil).Restore), ctx, id)
}

// Unpublish mocks base method.
func (m *MockService) Unpublish(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpublish", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unpublish indicates an expected call of Unpublish.
func (mr *MockServiceMockRecorder) Unpublish(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpublish", reflect.TypeOf((*MockService)(nil).Unpublish), ctx, id)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, req *course.UpdateRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, req)
}
