// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/services/product (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../test/services/product_mock/service_mock.go -package=product_mock . Service
//

// Package product_mock is a generated GoMock package.
package product_mock

import (
	context "context"
	reflect "reflect"

	product "github.com/mikhail5545/product-service-go/internal/models/product"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockService) Get(ctx context.Context, id string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService)(nil).Get), ctx, id)
}

// GetByDetailsID mocks base method.
func (m *MockService) GetByDetailsID(ctx context.Context, detailsID string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDetailsID indicates an expected call of GetByDetailsID.
func (mr *MockServiceMockRecorder) GetByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDetailsID", reflect.TypeOf((*MockService)(nil).GetByDetailsID), ctx, detailsID)
}

// GetWithDeleted mocks base method.
func (m *MockService) GetWithDeleted(ctx context.Context, id string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeleted", ctx, id)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeleted indicates an expected call of GetWithDeleted.
func (mr *MockServiceMockRecorder) GetWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeleted", reflect.TypeOf((*MockService)(nil).GetWithDeleted), ctx, id)
}

// GetWithDeletedByDetailsID mocks base method.
func (m *MockService) GetWithDeletedByDetailsID(ctx context.Context, detailsID string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeletedByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeletedByDetailsID indicates an expected call of GetWithDeletedByDetailsID.
func (mr *MockServiceMockRecorder) GetWithDeletedByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeletedByDetailsID", reflect.TypeOf((*MockService)(nil).GetWithDeletedByDetailsID), ctx, detailsID)
}

// GetWithUnpublished mocks base method.
func (m *MockService) GetWithUnpublished(ctx context.Context, id string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockServiceMockRecorder) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockService)(nil).GetWithUnpublished), ctx, id)
}

// GetWithUnpublishedByDetailsID mocks base method.
func (m *MockService) GetWithUnpublishedByDetailsID(ctx context.Context, detailsID string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublishedByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublishedByDetailsID indicates an expected call of GetWithUnpublishedByDetailsID.
func (mr *MockServiceMockRecorder) GetWithUnpublishedByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublishedByDetailsID", reflect.TypeOf((*MockService)(nil).GetWithUnpublishedByDetailsID), ctx, detailsID)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, limit, offset int) ([]product.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]product.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, limit, offset)
}

// ListByDetailsType mocks base method.
func (m *MockService) ListByDetailsType(ctx context.Context, detailsType string, limit, offset int) ([]product.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDetailsType", ctx, detailsType, limit, offset)
	ret0, _ := ret[0].([]product.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByDetailsType indicates an expected call of ListByDetailsType.
func (mr *MockServiceMockRecorder) ListByDetailsType(ctx, detailsType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDetailsType", reflect.TypeOf((*MockService)(nil).ListByDetailsType), ctx, detailsType, limit, offset)
}

// ListDeleted mocks base method.
func (m *MockService) ListDeleted(ctx context.Context, limit, offset int) ([]product.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeleted", ctx, limit, offset)
	ret0, _ := ret[0].([]product.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDeleted indicates an expected call of ListDeleted.
func (mr *MockServiceMockRecorder) ListDeleted(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeleted", reflect.TypeOf((*MockService)(nil).ListDeleted), ctx, limit, offset)
}

// ListUnpublished mocks base method.
func (m *MockService) ListUnpublished(ctx context.Context, limit, offset int) ([]product.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, limit, offset)
	ret0, _ := ret[0].([]product.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockServiceMockRecorder) ListUnpublished(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockService)(nil).ListUnpublished), ctx, limit, offset)
}
