// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/services/image (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../test/services/image_mock/service_mock.go -package=image_mock . Service
//

// Package image_mock is a generated GoMock package.
package image_mock

import (
	context "context"
	reflect "reflect"

	image "github.com/mikhail5545/product-service-go/internal/models/image"
	image_owner "github.com/mikhail5545/product-service-go/internal/types/image_owner"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockService) AddImage(ctx context.Context, req *image.AddRequest, ownerRepo image_owner.OwnerRepo[image_owner.Owner]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", ctx, req, ownerRepo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImage indicates an expected call of AddImage.
func (mr *MockServiceMockRecorder) AddImage(ctx, req, ownerRepo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockService)(nil).AddImage), ctx, req, ownerRepo)
}

// AddImageBatch mocks base method.
func (m *MockService) AddImageBatch(ctx context.Context, req *image.AddBatchRequest, ownerRepo image_owner.OwnerRepo[image_owner.Owner]) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImageBatch", ctx, req, ownerRepo)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddImageBatch indicates an expected call of AddImageBatch.
func (mr *MockServiceMockRecorder) AddImageBatch(ctx, req, ownerRepo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImageBatch", reflect.TypeOf((*MockService)(nil).AddImageBatch), ctx, req, ownerRepo)
}

// DeleteImage mocks base method.
func (m *MockService) DeleteImage(ctx context.Context, req *image.DeleteRequest, ownerRepo image_owner.OwnerRepo[image_owner.Owner]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, req, ownerRepo)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockServiceMockRecorder) DeleteImage(ctx, req, ownerRepo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockService)(nil).DeleteImage), ctx, req, ownerRepo)
}

// DeleteImageBatch mocks base method.
func (m *MockService) DeleteImageBatch(ctx context.Context, req *image.DeleteBatchRequst, ownerRepo image_owner.OwnerRepo[image_owner.Owner]) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImageBatch", ctx, req, ownerRepo)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteImageBatch indicates an expected call of DeleteImageBatch.
func (mr *MockServiceMockRecorder) DeleteImageBatch(ctx, req, ownerRepo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImageBatch", reflect.TypeOf((*MockService)(nil).DeleteImageBatch), ctx, req, ownerRepo)
}
