// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/database/course_part (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../test/database/course_part_mock/repo_mock.go -package=course_part_mock github.com/mikhail5545/product-service-go/internal/database/course_part Repository
//

// Package course_part_mock is a generated GoMock package.
package course_part_mock

import (
	context "context"
	reflect "reflect"

	coursepart "github.com/mikhail5545/product-service-go/internal/database/course_part"
	coursepart0 "github.com/mikhail5545/product-service-go/internal/models/course_part"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context, courseID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, courseID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx, courseID)
}

// CountDeleted mocks base method.
func (m *MockRepository) CountDeleted(ctx context.Context, courseID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDeleted", ctx, courseID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDeleted indicates an expected call of CountDeleted.
func (mr *MockRepositoryMockRecorder) CountDeleted(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDeleted", reflect.TypeOf((*MockRepository)(nil).CountDeleted), ctx, courseID)
}

// CountQuery mocks base method.
func (m *MockRepository) CountQuery(ctx context.Context, query any, args ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountQuery", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountQuery indicates an expected call of CountQuery.
func (mr *MockRepositoryMockRecorder) CountQuery(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountQuery", reflect.TypeOf((*MockRepository)(nil).CountQuery), varargs...)
}

// CountUnpublished mocks base method.
func (m *MockRepository) CountUnpublished(ctx context.Context, courseID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnpublished", ctx, courseID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnpublished indicates an expected call of CountUnpublished.
func (mr *MockRepositoryMockRecorder) CountUnpublished(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnpublished", reflect.TypeOf((*MockRepository)(nil).CountUnpublished), ctx, courseID)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, coursePart *coursepart0.CoursePart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, coursePart)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, coursePart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, coursePart)
}

// DB mocks base method.
func (m *MockRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockRepository)(nil).DB))
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// DeleteByCourseID mocks base method.
func (m *MockRepository) DeleteByCourseID(ctx context.Context, courseID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCourseID", ctx, courseID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByCourseID indicates an expected call of DeleteByCourseID.
func (mr *MockRepositoryMockRecorder) DeleteByCourseID(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCourseID", reflect.TypeOf((*MockRepository)(nil).DeleteByCourseID), ctx, courseID)
}

// DeletePermanent mocks base method.
func (m *MockRepository) DeletePermanent(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanent", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermanent indicates an expected call of DeletePermanent.
func (mr *MockRepositoryMockRecorder) DeletePermanent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanent", reflect.TypeOf((*MockRepository)(nil).DeletePermanent), ctx, id)
}

// DeletePermanentByCourseID mocks base method.
func (m *MockRepository) DeletePermanentByCourseID(ctx context.Context, courseID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanentByCourseID", ctx, courseID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermanentByCourseID indicates an expected call of DeletePermanentByCourseID.
func (mr *MockRepositoryMockRecorder) DeletePermanentByCourseID(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanentByCourseID", reflect.TypeOf((*MockRepository)(nil).DeletePermanentByCourseID), ctx, courseID)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id string) (*coursepart0.CoursePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*coursepart0.CoursePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// GetWithDeleted mocks base method.
func (m *MockRepository) GetWithDeleted(ctx context.Context, id string) (*coursepart0.CoursePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeleted", ctx, id)
	ret0, _ := ret[0].(*coursepart0.CoursePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeleted indicates an expected call of GetWithDeleted.
func (mr *MockRepositoryMockRecorder) GetWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeleted", reflect.TypeOf((*MockRepository)(nil).GetWithDeleted), ctx, id)
}

// GetWithUnpublished mocks base method.
func (m *MockRepository) GetWithUnpublished(ctx context.Context, id string) (*coursepart0.CoursePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(*coursepart0.CoursePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockRepositoryMockRecorder) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockRepository)(nil).GetWithUnpublished), ctx, id)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, courseID string, limit, offset int) ([]coursepart0.CoursePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, courseID, limit, offset)
	ret0, _ := ret[0].([]coursepart0.CoursePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, courseID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, courseID, limit, offset)
}

// ListDeleted mocks base method.
func (m *MockRepository) ListDeleted(ctx context.Context, courseID string, limit, offset int) ([]coursepart0.CoursePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeleted", ctx, courseID, limit, offset)
	ret0, _ := ret[0].([]coursepart0.CoursePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeleted indicates an expected call of ListDeleted.
func (mr *MockRepositoryMockRecorder) ListDeleted(ctx, courseID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeleted", reflect.TypeOf((*MockRepository)(nil).ListDeleted), ctx, courseID, limit, offset)
}

// ListUnpublished mocks base method.
func (m *MockRepository) ListUnpublished(ctx context.Context, courseID string, limit, offset int) ([]coursepart0.CoursePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, courseID, limit, offset)
	ret0, _ := ret[0].([]coursepart0.CoursePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockRepositoryMockRecorder) ListUnpublished(ctx, courseID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockRepository)(nil).ListUnpublished), ctx, courseID, limit, offset)
}

// Restore mocks base method.
func (m *MockRepository) Restore(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRepository)(nil).Restore), ctx, id)
}

// RestoreByCourseID mocks base method.
func (m *MockRepository) RestoreByCourseID(ctx context.Context, courseID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreByCourseID", ctx, courseID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreByCourseID indicates an expected call of RestoreByCourseID.
func (mr *MockRepositoryMockRecorder) RestoreByCourseID(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreByCourseID", reflect.TypeOf((*MockRepository)(nil).RestoreByCourseID), ctx, courseID)
}

// Select mocks base method.
func (m *MockRepository) Select(ctx context.Context, id string, fields ...string) (*coursepart0.CoursePart, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Select", varargs...)
	ret0, _ := ret[0].(*coursepart0.CoursePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepositoryMockRecorder) Select(ctx, id any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepository)(nil).Select), varargs...)
}

// SetPublished mocks base method.
func (m *MockRepository) SetPublished(ctx context.Context, id string, published bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublished", ctx, id, published)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPublished indicates an expected call of SetPublished.
func (mr *MockRepositoryMockRecorder) SetPublished(ctx, id, published any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublished", reflect.TypeOf((*MockRepository)(nil).SetPublished), ctx, id, published)
}

// SetPublishedByCourseID mocks base method.
func (m *MockRepository) SetPublishedByCourseID(ctx context.Context, courseID string, published bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublishedByCourseID", ctx, courseID, published)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPublishedByCourseID indicates an expected call of SetPublishedByCourseID.
func (mr *MockRepositoryMockRecorder) SetPublishedByCourseID(ctx, courseID, published any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublishedByCourseID", reflect.TypeOf((*MockRepository)(nil).SetPublishedByCourseID), ctx, courseID, published)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, coursePart *coursepart0.CoursePart, updates any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, coursePart, updates)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, coursePart, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, coursePart, updates)
}

// UpdateVideoID mocks base method.
func (m *MockRepository) UpdateVideoID(ctx context.Context, id string, videoID *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoID", ctx, id, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoID indicates an expected call of UpdateVideoID.
func (mr *MockRepositoryMockRecorder) UpdateVideoID(ctx, id, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoID", reflect.TypeOf((*MockRepository)(nil).UpdateVideoID), ctx, id, videoID)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *gorm.DB) coursepart.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(coursepart.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
