// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/database/course (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../test/database/course_mock/repo_mock.go -package=course_mock github.com/mikhail5545/product-service-go/internal/database/course Repository
//

// Package course_mock is a generated GoMock package.
package course_mock

import (
	context "context"
	reflect "reflect"

	course "github.com/mikhail5545/product-service-go/internal/database/course"
	course0 "github.com/mikhail5545/product-service-go/internal/models/course"
	image "github.com/mikhail5545/product-service-go/internal/models/image"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockRepository) AddImage(ctx context.Context, arg1 *course0.Course, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", ctx, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImage indicates an expected call of AddImage.
func (mr *MockRepositoryMockRecorder) AddImage(ctx, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockRepository)(nil).AddImage), ctx, arg1, arg2)
}

// AddImageBatch mocks base method.
func (m *MockRepository) AddImageBatch(ctx context.Context, courses []course0.Course, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImageBatch", ctx, courses, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImageBatch indicates an expected call of AddImageBatch.
func (mr *MockRepositoryMockRecorder) AddImageBatch(ctx, courses, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImageBatch", reflect.TypeOf((*MockRepository)(nil).AddImageBatch), ctx, courses, arg2)
}

// BatchUpdate mocks base method.
func (m *MockRepository) BatchUpdate(ctx context.Context, updates []course0.Course, opt uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, updates, opt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockRepositoryMockRecorder) BatchUpdate(ctx, updates, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockRepository)(nil).BatchUpdate), ctx, updates, opt)
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx)
}

// CountDeleted mocks base method.
func (m *MockRepository) CountDeleted(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDeleted", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDeleted indicates an expected call of CountDeleted.
func (mr *MockRepositoryMockRecorder) CountDeleted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDeleted", reflect.TypeOf((*MockRepository)(nil).CountDeleted), ctx)
}

// CountUnpublished mocks base method.
func (m *MockRepository) CountUnpublished(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnpublished", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnpublished indicates an expected call of CountUnpublished.
func (mr *MockRepositoryMockRecorder) CountUnpublished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnpublished", reflect.TypeOf((*MockRepository)(nil).CountUnpublished), ctx)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *course0.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// DB mocks base method.
func (m *MockRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockRepository)(nil).DB))
}

// DecrementImageCount mocks base method.
func (m *MockRepository) DecrementImageCount(ctx context.Context, courseIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementImageCount", ctx, courseIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementImageCount indicates an expected call of DecrementImageCount.
func (mr *MockRepositoryMockRecorder) DecrementImageCount(ctx, courseIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementImageCount", reflect.TypeOf((*MockRepository)(nil).DecrementImageCount), ctx, courseIDs)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// DeleteImage mocks base method.
func (m *MockRepository) DeleteImage(ctx context.Context, arg1 *course0.Course, mediaSvcID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, arg1, mediaSvcID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockRepositoryMockRecorder) DeleteImage(ctx, arg1, mediaSvcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockRepository)(nil).DeleteImage), ctx, arg1, mediaSvcID)
}

// DeleteImageBatch mocks base method.
func (m *MockRepository) DeleteImageBatch(ctx context.Context, courses []course0.Course, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImageBatch", ctx, courses, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImageBatch indicates an expected call of DeleteImageBatch.
func (mr *MockRepositoryMockRecorder) DeleteImageBatch(ctx, courses, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImageBatch", reflect.TypeOf((*MockRepository)(nil).DeleteImageBatch), ctx, courses, arg2)
}

// DeletePermanent mocks base method.
func (m *MockRepository) DeletePermanent(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanent", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermanent indicates an expected call of DeletePermanent.
func (mr *MockRepositoryMockRecorder) DeletePermanent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanent", reflect.TypeOf((*MockRepository)(nil).DeletePermanent), ctx, id)
}

// FindOwnerIDsByImageID mocks base method.
func (m *MockRepository) FindOwnerIDsByImageID(ctx context.Context, mediaSvcID string, ownerIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOwnerIDsByImageID", ctx, mediaSvcID, ownerIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOwnerIDsByImageID indicates an expected call of FindOwnerIDsByImageID.
func (mr *MockRepositoryMockRecorder) FindOwnerIDsByImageID(ctx, mediaSvcID, ownerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOwnerIDsByImageID", reflect.TypeOf((*MockRepository)(nil).FindOwnerIDsByImageID), ctx, mediaSvcID, ownerIDs)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id string) (*course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// GetReduced mocks base method.
func (m *MockRepository) GetReduced(ctx context.Context, id string) (*course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReduced", ctx, id)
	ret0, _ := ret[0].(*course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReduced indicates an expected call of GetReduced.
func (mr *MockRepositoryMockRecorder) GetReduced(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReduced", reflect.TypeOf((*MockRepository)(nil).GetReduced), ctx, id)
}

// GetReducedWithDeleted mocks base method.
func (m *MockRepository) GetReducedWithDeleted(ctx context.Context, id string) (*course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReducedWithDeleted", ctx, id)
	ret0, _ := ret[0].(*course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReducedWithDeleted indicates an expected call of GetReducedWithDeleted.
func (mr *MockRepositoryMockRecorder) GetReducedWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReducedWithDeleted", reflect.TypeOf((*MockRepository)(nil).GetReducedWithDeleted), ctx, id)
}

// GetReducedWithUnpublished mocks base method.
func (m *MockRepository) GetReducedWithUnpublished(ctx context.Context, id string) (*course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReducedWithUnpublished", ctx, id)
	ret0, _ := ret[0].(*course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReducedWithUnpublished indicates an expected call of GetReducedWithUnpublished.
func (mr *MockRepositoryMockRecorder) GetReducedWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReducedWithUnpublished", reflect.TypeOf((*MockRepository)(nil).GetReducedWithUnpublished), ctx, id)
}

// GetWithDeleted mocks base method.
func (m *MockRepository) GetWithDeleted(ctx context.Context, id string) (*course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeleted", ctx, id)
	ret0, _ := ret[0].(*course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeleted indicates an expected call of GetWithDeleted.
func (mr *MockRepositoryMockRecorder) GetWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeleted", reflect.TypeOf((*MockRepository)(nil).GetWithDeleted), ctx, id)
}

// GetWithUnpublished mocks base method.
func (m *MockRepository) GetWithUnpublished(ctx context.Context, id string) (*course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(*course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockRepositoryMockRecorder) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockRepository)(nil).GetWithUnpublished), ctx, id)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, limit, offset int) ([]course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, limit, offset)
}

// ListDeleted mocks base method.
func (m *MockRepository) ListDeleted(ctx context.Context, limit, offset int) ([]course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeleted", ctx, limit, offset)
	ret0, _ := ret[0].([]course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeleted indicates an expected call of ListDeleted.
func (mr *MockRepositoryMockRecorder) ListDeleted(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeleted", reflect.TypeOf((*MockRepository)(nil).ListDeleted), ctx, limit, offset)
}

// ListUnpublished mocks base method.
func (m *MockRepository) ListUnpublished(ctx context.Context, limit, offset int) ([]course0.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, limit, offset)
	ret0, _ := ret[0].([]course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockRepositoryMockRecorder) ListUnpublished(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockRepository)(nil).ListUnpublished), ctx, limit, offset)
}

// ListWithUnpublishedByIDs mocks base method.
func (m *MockRepository) ListWithUnpublishedByIDs(ctx context.Context, ids ...string) ([]course0.Course, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListWithUnpublishedByIDs", varargs...)
	ret0, _ := ret[0].([]course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithUnpublishedByIDs indicates an expected call of ListWithUnpublishedByIDs.
func (mr *MockRepositoryMockRecorder) ListWithUnpublishedByIDs(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithUnpublishedByIDs", reflect.TypeOf((*MockRepository)(nil).ListWithUnpublishedByIDs), varargs...)
}

// Restore mocks base method.
func (m *MockRepository) Restore(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRepository)(nil).Restore), ctx, id)
}

// Select mocks base method.
func (m *MockRepository) Select(ctx context.Context, id string, fields ...string) (*course0.Course, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Select", varargs...)
	ret0, _ := ret[0].(*course0.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepositoryMockRecorder) Select(ctx, id any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepository)(nil).Select), varargs...)
}

// SetInStock mocks base method.
func (m *MockRepository) SetInStock(ctx context.Context, id string, inStock bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInStock", ctx, id, inStock)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInStock indicates an expected call of SetInStock.
func (mr *MockRepositoryMockRecorder) SetInStock(ctx, id, inStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInStock", reflect.TypeOf((*MockRepository)(nil).SetInStock), ctx, id, inStock)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *course0.Course, updates any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1, updates)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1, updates)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *gorm.DB) course.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(course.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
