// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/database/product (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../test/database/product_mock/repo_mock.go -package=product_mock github.com/mikhail5545/product-service-go/internal/database/product Repository
//

// Package product_mock is a generated GoMock package.
package product_mock

import (
	context "context"
	reflect "reflect"

	product "github.com/mikhail5545/product-service-go/internal/database/product"
	product0 "github.com/mikhail5545/product-service-go/internal/models/product"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx)
}

// CountByDetailsType mocks base method.
func (m *MockRepository) CountByDetailsType(ctx context.Context, detailsType string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByDetailsType", ctx, detailsType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByDetailsType indicates an expected call of CountByDetailsType.
func (mr *MockRepositoryMockRecorder) CountByDetailsType(ctx, detailsType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByDetailsType", reflect.TypeOf((*MockRepository)(nil).CountByDetailsType), ctx, detailsType)
}

// CountDeleted mocks base method.
func (m *MockRepository) CountDeleted(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDeleted", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDeleted indicates an expected call of CountDeleted.
func (mr *MockRepositoryMockRecorder) CountDeleted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDeleted", reflect.TypeOf((*MockRepository)(nil).CountDeleted), ctx)
}

// CountUnpublished mocks base method.
func (m *MockRepository) CountUnpublished(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnpublished", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnpublished indicates an expected call of CountUnpublished.
func (mr *MockRepositoryMockRecorder) CountUnpublished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnpublished", reflect.TypeOf((*MockRepository)(nil).CountUnpublished), ctx)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *product0.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// CreateBatch mocks base method.
func (m *MockRepository) CreateBatch(ctx context.Context, products ...*product0.Product) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range products {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateBatch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockRepositoryMockRecorder) CreateBatch(ctx any, products ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, products...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockRepository)(nil).CreateBatch), varargs...)
}

// DB mocks base method.
func (m *MockRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockRepository)(nil).DB))
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// DeleteByDetailsID mocks base method.
func (m *MockRepository) DeleteByDetailsID(ctx context.Context, detailsID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByDetailsID indicates an expected call of DeleteByDetailsID.
func (mr *MockRepositoryMockRecorder) DeleteByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByDetailsID", reflect.TypeOf((*MockRepository)(nil).DeleteByDetailsID), ctx, detailsID)
}

// DeletePermanent mocks base method.
func (m *MockRepository) DeletePermanent(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanent", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermanent indicates an expected call of DeletePermanent.
func (mr *MockRepositoryMockRecorder) DeletePermanent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanent", reflect.TypeOf((*MockRepository)(nil).DeletePermanent), ctx, id)
}

// DeletePermanentByDetailsID mocks base method.
func (m *MockRepository) DeletePermanentByDetailsID(ctx context.Context, detailsID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanentByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermanentByDetailsID indicates an expected call of DeletePermanentByDetailsID.
func (mr *MockRepositoryMockRecorder) DeletePermanentByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanentByDetailsID", reflect.TypeOf((*MockRepository)(nil).DeletePermanentByDetailsID), ctx, detailsID)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// GetByDetailsID mocks base method.
func (m *MockRepository) GetByDetailsID(ctx context.Context, detailsID string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDetailsID indicates an expected call of GetByDetailsID.
func (mr *MockRepositoryMockRecorder) GetByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDetailsID", reflect.TypeOf((*MockRepository)(nil).GetByDetailsID), ctx, detailsID)
}

// GetWithDeleted mocks base method.
func (m *MockRepository) GetWithDeleted(ctx context.Context, id string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeleted", ctx, id)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeleted indicates an expected call of GetWithDeleted.
func (mr *MockRepositoryMockRecorder) GetWithDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeleted", reflect.TypeOf((*MockRepository)(nil).GetWithDeleted), ctx, id)
}

// GetWithDeletedByDetailsID mocks base method.
func (m *MockRepository) GetWithDeletedByDetailsID(ctx context.Context, detailsID string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDeletedByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDeletedByDetailsID indicates an expected call of GetWithDeletedByDetailsID.
func (mr *MockRepositoryMockRecorder) GetWithDeletedByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDeletedByDetailsID", reflect.TypeOf((*MockRepository)(nil).GetWithDeletedByDetailsID), ctx, detailsID)
}

// GetWithUnpublished mocks base method.
func (m *MockRepository) GetWithUnpublished(ctx context.Context, id string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockRepositoryMockRecorder) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockRepository)(nil).GetWithUnpublished), ctx, id)
}

// GetWithUnpublishedByDetailsID mocks base method.
func (m *MockRepository) GetWithUnpublishedByDetailsID(ctx context.Context, detailsID string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublishedByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublishedByDetailsID indicates an expected call of GetWithUnpublishedByDetailsID.
func (mr *MockRepositoryMockRecorder) GetWithUnpublishedByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublishedByDetailsID", reflect.TypeOf((*MockRepository)(nil).GetWithUnpublishedByDetailsID), ctx, detailsID)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, limit, offset int) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, limit, offset)
}

// ListByDetailsType mocks base method.
func (m *MockRepository) ListByDetailsType(ctx context.Context, detailsType string, limit, offset int) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDetailsType", ctx, detailsType, limit, offset)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDetailsType indicates an expected call of ListByDetailsType.
func (mr *MockRepositoryMockRecorder) ListByDetailsType(ctx, detailsType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDetailsType", reflect.TypeOf((*MockRepository)(nil).ListByDetailsType), ctx, detailsType, limit, offset)
}

// ListByIDs mocks base method.
func (m *MockRepository) ListByIDs(ctx context.Context, ids []string) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockRepositoryMockRecorder) ListByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockRepository)(nil).ListByIDs), ctx, ids)
}

// ListDeleted mocks base method.
func (m *MockRepository) ListDeleted(ctx context.Context, limit, offset int) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeleted", ctx, limit, offset)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeleted indicates an expected call of ListDeleted.
func (mr *MockRepositoryMockRecorder) ListDeleted(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeleted", reflect.TypeOf((*MockRepository)(nil).ListDeleted), ctx, limit, offset)
}

// ListUnpublished mocks base method.
func (m *MockRepository) ListUnpublished(ctx context.Context, limit, offset int) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, limit, offset)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockRepositoryMockRecorder) ListUnpublished(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockRepository)(nil).ListUnpublished), ctx, limit, offset)
}

// Restore mocks base method.
func (m *MockRepository) Restore(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRepository)(nil).Restore), ctx, id)
}

// RestoreByDetailsID mocks base method.
func (m *MockRepository) RestoreByDetailsID(ctx context.Context, detailsID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreByDetailsID", ctx, detailsID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreByDetailsID indicates an expected call of RestoreByDetailsID.
func (mr *MockRepositoryMockRecorder) RestoreByDetailsID(ctx, detailsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreByDetailsID", reflect.TypeOf((*MockRepository)(nil).RestoreByDetailsID), ctx, detailsID)
}

// Select mocks base method.
func (m *MockRepository) Select(ctx context.Context, id string, fields []string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, id, fields)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepositoryMockRecorder) Select(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepository)(nil).Select), ctx, id, fields)
}

// SelectByDetailsID mocks base method.
func (m *MockRepository) SelectByDetailsID(ctx context.Context, detailsID string, fields ...string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, detailsID}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectByDetailsID", varargs...)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByDetailsID indicates an expected call of SelectByDetailsID.
func (mr *MockRepositoryMockRecorder) SelectByDetailsID(ctx, detailsID any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, detailsID}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByDetailsID", reflect.TypeOf((*MockRepository)(nil).SelectByDetailsID), varargs...)
}

// SelectByDetailsIDs mocks base method.
func (m *MockRepository) SelectByDetailsIDs(ctx context.Context, detailsIDs []string, fields ...string) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, detailsIDs}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectByDetailsIDs", varargs...)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByDetailsIDs indicates an expected call of SelectByDetailsIDs.
func (mr *MockRepositoryMockRecorder) SelectByDetailsIDs(ctx, detailsIDs any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, detailsIDs}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByDetailsIDs", reflect.TypeOf((*MockRepository)(nil).SelectByDetailsIDs), varargs...)
}

// SelectByIDs mocks base method.
func (m *MockRepository) SelectByIDs(ctx context.Context, ids []string, fields ...string) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ids}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectByIDs", varargs...)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByIDs indicates an expected call of SelectByIDs.
func (mr *MockRepositoryMockRecorder) SelectByIDs(ctx, ids any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ids}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByIDs", reflect.TypeOf((*MockRepository)(nil).SelectByIDs), varargs...)
}

// SelectWithDeletedByDetailsID mocks base method.
func (m *MockRepository) SelectWithDeletedByDetailsID(ctx context.Context, detailsID string, fields ...string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, detailsID}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectWithDeletedByDetailsID", varargs...)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectWithDeletedByDetailsID indicates an expected call of SelectWithDeletedByDetailsID.
func (mr *MockRepositoryMockRecorder) SelectWithDeletedByDetailsID(ctx, detailsID any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, detailsID}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWithDeletedByDetailsID", reflect.TypeOf((*MockRepository)(nil).SelectWithDeletedByDetailsID), varargs...)
}

// SelectWithDeletedByDetailsIDs mocks base method.
func (m *MockRepository) SelectWithDeletedByDetailsIDs(ctx context.Context, detailsIDs []string, fields ...string) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, detailsIDs}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectWithDeletedByDetailsIDs", varargs...)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectWithDeletedByDetailsIDs indicates an expected call of SelectWithDeletedByDetailsIDs.
func (mr *MockRepositoryMockRecorder) SelectWithDeletedByDetailsIDs(ctx, detailsIDs any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, detailsIDs}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWithDeletedByDetailsIDs", reflect.TypeOf((*MockRepository)(nil).SelectWithDeletedByDetailsIDs), varargs...)
}

// SelectWithDeletedByIDs mocks base method.
func (m *MockRepository) SelectWithDeletedByIDs(ctx context.Context, ids []string, fields ...string) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ids}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectWithDeletedByIDs", varargs...)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectWithDeletedByIDs indicates an expected call of SelectWithDeletedByIDs.
func (mr *MockRepositoryMockRecorder) SelectWithDeletedByIDs(ctx, ids any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ids}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWithDeletedByIDs", reflect.TypeOf((*MockRepository)(nil).SelectWithDeletedByIDs), varargs...)
}

// SelectWithUnpublishedByDetailsID mocks base method.
func (m *MockRepository) SelectWithUnpublishedByDetailsID(ctx context.Context, detailsID string, fields ...string) (*product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, detailsID}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectWithUnpublishedByDetailsID", varargs...)
	ret0, _ := ret[0].(*product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectWithUnpublishedByDetailsID indicates an expected call of SelectWithUnpublishedByDetailsID.
func (mr *MockRepositoryMockRecorder) SelectWithUnpublishedByDetailsID(ctx, detailsID any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, detailsID}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWithUnpublishedByDetailsID", reflect.TypeOf((*MockRepository)(nil).SelectWithUnpublishedByDetailsID), varargs...)
}

// SelectWithUnpublishedByDetailsIDs mocks base method.
func (m *MockRepository) SelectWithUnpublishedByDetailsIDs(ctx context.Context, detailsIDs []string, fields ...string) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, detailsIDs}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectWithUnpublishedByDetailsIDs", varargs...)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectWithUnpublishedByDetailsIDs indicates an expected call of SelectWithUnpublishedByDetailsIDs.
func (mr *MockRepositoryMockRecorder) SelectWithUnpublishedByDetailsIDs(ctx, detailsIDs any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, detailsIDs}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWithUnpublishedByDetailsIDs", reflect.TypeOf((*MockRepository)(nil).SelectWithUnpublishedByDetailsIDs), varargs...)
}

// SelectWithUnpublishedByIDs mocks base method.
func (m *MockRepository) SelectWithUnpublishedByIDs(ctx context.Context, ids []string, fields ...string) ([]product0.Product, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ids}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectWithUnpublishedByIDs", varargs...)
	ret0, _ := ret[0].([]product0.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectWithUnpublishedByIDs indicates an expected call of SelectWithUnpublishedByIDs.
func (mr *MockRepositoryMockRecorder) SelectWithUnpublishedByIDs(ctx, ids any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ids}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWithUnpublishedByIDs", reflect.TypeOf((*MockRepository)(nil).SelectWithUnpublishedByIDs), varargs...)
}

// SetInStock mocks base method.
func (m *MockRepository) SetInStock(ctx context.Context, id string, inStock bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInStock", ctx, id, inStock)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInStock indicates an expected call of SetInStock.
func (mr *MockRepositoryMockRecorder) SetInStock(ctx, id, inStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInStock", reflect.TypeOf((*MockRepository)(nil).SetInStock), ctx, id, inStock)
}

// SetInStockByDetailsID mocks base method.
func (m *MockRepository) SetInStockByDetailsID(ctx context.Context, detailsID string, inStock bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInStockByDetailsID", ctx, detailsID, inStock)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInStockByDetailsID indicates an expected call of SetInStockByDetailsID.
func (mr *MockRepositoryMockRecorder) SetInStockByDetailsID(ctx, detailsID, inStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInStockByDetailsID", reflect.TypeOf((*MockRepository)(nil).SetInStockByDetailsID), ctx, detailsID, inStock)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *product0.Product, updates any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1, updates)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1, updates)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *gorm.DB) product.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(product.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
