// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/product-service-go/internal/types/image_owner (interfaces: OwnerRepo)
//
// Generated by this command:
//
//	mockgen -destination=../../test/types/image_owner_mock/repo_mock.go -package=image_owner_mock . OwnerRepo
//

// Package image_owner_mock is a generated GoMock package.
package image_owner_mock

import (
	context "context"
	reflect "reflect"

	image "github.com/mikhail5545/product-service-go/internal/models/image"
	image_owner "github.com/mikhail5545/product-service-go/internal/types/image_owner"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOwnerRepo is a mock of OwnerRepo interface.
type MockOwnerRepo[T image_owner.Owner] struct {
	ctrl     *gomock.Controller
	recorder *MockOwnerRepoMockRecorder[T]
	isgomock struct{}
}

// MockOwnerRepoMockRecorder is the mock recorder for MockOwnerRepo.
type MockOwnerRepoMockRecorder[T image_owner.Owner] struct {
	mock *MockOwnerRepo[T]
}

// NewMockOwnerRepo creates a new mock instance.
func NewMockOwnerRepo[T image_owner.Owner](ctrl *gomock.Controller) *MockOwnerRepo[T] {
	mock := &MockOwnerRepo[T]{ctrl: ctrl}
	mock.recorder = &MockOwnerRepoMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnerRepo[T]) EXPECT() *MockOwnerRepoMockRecorder[T] {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockOwnerRepo[T]) AddImage(ctx context.Context, owner T, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", ctx, owner, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImage indicates an expected call of AddImage.
func (mr *MockOwnerRepoMockRecorder[T]) AddImage(ctx, owner, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockOwnerRepo[T])(nil).AddImage), ctx, owner, arg2)
}

// AddImageBatch mocks base method.
func (m *MockOwnerRepo[T]) AddImageBatch(ctx context.Context, owners []T, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImageBatch", ctx, owners, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImageBatch indicates an expected call of AddImageBatch.
func (mr *MockOwnerRepoMockRecorder[T]) AddImageBatch(ctx, owners, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImageBatch", reflect.TypeOf((*MockOwnerRepo[T])(nil).AddImageBatch), ctx, owners, arg2)
}

// BatchUpdate mocks base method.
func (m *MockOwnerRepo[T]) BatchUpdate(ctx context.Context, owners []T, opt uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, owners, opt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockOwnerRepoMockRecorder[T]) BatchUpdate(ctx, owners, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockOwnerRepo[T])(nil).BatchUpdate), ctx, owners, opt)
}

// DB mocks base method.
func (m *MockOwnerRepo[T]) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockOwnerRepoMockRecorder[T]) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockOwnerRepo[T])(nil).DB))
}

// DecrementImageCount mocks base method.
func (m *MockOwnerRepo[T]) DecrementImageCount(ctx context.Context, ownerIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementImageCount", ctx, ownerIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementImageCount indicates an expected call of DecrementImageCount.
func (mr *MockOwnerRepoMockRecorder[T]) DecrementImageCount(ctx, ownerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementImageCount", reflect.TypeOf((*MockOwnerRepo[T])(nil).DecrementImageCount), ctx, ownerIDs)
}

// DeleteImage mocks base method.
func (m *MockOwnerRepo[T]) DeleteImage(ctx context.Context, owner T, mediaSvcID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, owner, mediaSvcID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockOwnerRepoMockRecorder[T]) DeleteImage(ctx, owner, mediaSvcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockOwnerRepo[T])(nil).DeleteImage), ctx, owner, mediaSvcID)
}

// DeleteImageBatch mocks base method.
func (m *MockOwnerRepo[T]) DeleteImageBatch(ctx context.Context, owners []T, arg2 *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImageBatch", ctx, owners, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImageBatch indicates an expected call of DeleteImageBatch.
func (mr *MockOwnerRepoMockRecorder[T]) DeleteImageBatch(ctx, owners, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImageBatch", reflect.TypeOf((*MockOwnerRepo[T])(nil).DeleteImageBatch), ctx, owners, arg2)
}

// FindOwnerIDsByImageID mocks base method.
func (m *MockOwnerRepo[T]) FindOwnerIDsByImageID(ctx context.Context, mediaSvcID string, ownerIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOwnerIDsByImageID", ctx, mediaSvcID, ownerIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOwnerIDsByImageID indicates an expected call of FindOwnerIDsByImageID.
func (mr *MockOwnerRepoMockRecorder[T]) FindOwnerIDsByImageID(ctx, mediaSvcID, ownerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOwnerIDsByImageID", reflect.TypeOf((*MockOwnerRepo[T])(nil).FindOwnerIDsByImageID), ctx, mediaSvcID, ownerIDs)
}

// GetWithUnpublished mocks base method.
func (m *MockOwnerRepo[T]) GetWithUnpublished(ctx context.Context, id string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithUnpublished", ctx, id)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithUnpublished indicates an expected call of GetWithUnpublished.
func (mr *MockOwnerRepoMockRecorder[T]) GetWithUnpublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithUnpublished", reflect.TypeOf((*MockOwnerRepo[T])(nil).GetWithUnpublished), ctx, id)
}

// ListWithUnpublishedByIDs mocks base method.
func (m *MockOwnerRepo[T]) ListWithUnpublishedByIDs(ctx context.Context, ids ...string) ([]T, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListWithUnpublishedByIDs", varargs...)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithUnpublishedByIDs indicates an expected call of ListWithUnpublishedByIDs.
func (mr *MockOwnerRepoMockRecorder[T]) ListWithUnpublishedByIDs(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithUnpublishedByIDs", reflect.TypeOf((*MockOwnerRepo[T])(nil).ListWithUnpublishedByIDs), varargs...)
}

// WithTx mocks base method.
func (m *MockOwnerRepo[T]) WithTx(tx *gorm.DB) image_owner.OwnerRepo[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(image_owner.OwnerRepo[T])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockOwnerRepoMockRecorder[T]) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockOwnerRepo[T])(nil).WithTx), tx)
}
